spring:
  cloud:
   gateway:
     server:
       webflux:
         routes:
           - id: m1
             uri: lb://customer-service
             predicates:
               - Path=/api/customers/**
           - id: m2
             uri: lb://inventory-service
             predicates:
               - Path=/api/products/**

